# Generated by Django 2.1.13 on 2020-01-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PendienteEnviar', '0002_facturasxcliente_idcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_FacturasxCliente',
            fields=[
                ('IDFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=50)),
                ('Cliente', models.CharField(max_length=100)),
                ('IDCliente', models.IntegerField(default=0)),
                ('FechaFactura', models.DateTimeField()),
                ('Subtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Retencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Saldo', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('RutaXML', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=15)),
                ('IsAutorizada', models.BooleanField()),
                ('Moneda', models.CharField(max_length=10)),
                ('IsFragmentada', models.BooleanField()),
            ],
            options={
                'db_table': 'View_FacturasxCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CobrosxCliente',
            fields=[
                ('IDCobro', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Folio', models.CharField(max_length=50, unique=True)),
                ('RutaPDF', models.CharField(max_length=300)),
                ('RutaXML', models.CharField(max_length=300)),
                ('FechaCobro', models.DateTimeField()),
                ('Comentarios', models.CharField(default='', max_length=500)),
                ('TipoCambio', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('IDCliente', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CobrosxCliente',
            },
        ),
        migrations.CreateModel(
            name='CobrosxFacturas',
            fields=[
                ('IDCobroxFactura', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'CobrosxFacturas',
            },
        ),
        migrations.CreateModel(
            name='RelacionCobrosFacturasxCliente',
            fields=[
                ('IDRelacionCobroFacturasxCliente', models.AutoField(primary_key=True, serialize=False)),
                ('IDUsuarioAlta', models.IntegerField(default=0)),
                ('IDCobro', models.ForeignKey(db_column='IDCobro', on_delete=django.db.models.deletion.CASCADE, to='EstadosdeCuenta.CobrosxCliente')),
                ('IDCobroxFactura', models.ForeignKey(db_column='IDCobroxFactura', on_delete=django.db.models.deletion.CASCADE, to='EstadosdeCuenta.CobrosxFacturas')),
                ('IDFactura', models.ForeignKey(db_column='IDFactura', on_delete=django.db.models.deletion.CASCADE, to='PendienteEnviar.FacturasxCliente')),
            ],
            options={
                'db_table': 'RelacionCobrosFacturasxCliente',
            },
        ),
    ]
