# Generated by Django 2.1.13 on 2019-11-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosdeCuenta', '0003_relacionconceptoxproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrosxCliente',
            fields=[
                ('IDCobro', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('RutaPDF', models.CharField(max_length=300)),
                ('RutaXML', models.CharField(max_length=300)),
                ('FechaCobro', models.DateTimeField()),
            ],
            options={
                'db_table': 'CobrosxCliente',
            },
        ),
        migrations.CreateModel(
            name='CobrosxFacturas',
            fields=[
                ('IDCobroxFactura', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
            ],
            options={
                'db_table': 'CobrosxFacturas',
            },
        ),
        migrations.CreateModel(
            name='RelacionCobrosFacturasxCliente',
            fields=[
                ('IDRelacionCobroFacturasxCliente', models.AutoField(primary_key=True, serialize=False)),
                ('IDUsuarioAlta', models.IntegerField(default=0)),
                ('IDCliente', models.IntegerField(default=0)),
                ('IDCobro', models.ForeignKey(db_column='IDCobro', on_delete=django.db.models.deletion.CASCADE, to='EstadosdeCuenta.CobrosxCliente')),
                ('IDCobroxFactura', models.ForeignKey(db_column='IDCobroxFactura', on_delete=django.db.models.deletion.CASCADE, to='EstadosdeCuenta.CobrosxFacturas')),
                ('IDFactura', models.ForeignKey(db_column='IDFactura', on_delete=django.db.models.deletion.CASCADE, to='EstadosdeCuenta.FacturasxCliente')),
            ],
            options={
                'db_table': 'RelacionCobrosFacturasxCliente',
            },
        ),
    ]
