# Generated by Django 2.1.13 on 2019-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosdeCuenta', '0004_cobrosxcliente_cobrosxfacturas_relacioncobrosfacturasxcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrosxcliente',
            name='Comentarios',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cobrosxcliente',
            name='TipoCambio',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=10),
        ),
    ]
