# Generated by Django 2.1.13 on 2019-11-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosdeCuenta', '0005_auto_20191125_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrosxcliente',
            name='NombreCortoCliente',
            field=models.CharField(default='Eaton', max_length=100),
            preserve_default=False,
        ),
    ]
