# Generated by Django 2.1.13 on 2019-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstadosdeCuenta', '0006_cobrosxcliente_nombrecortocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrosxcliente',
            name='Folio',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
