# Generated by Django 2.1.13 on 2020-01-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IDCliente', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCorto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'AdmonClientes',
                'managed': False,
            },
        ),
    ]
