# Generated by Django 2.1.13 on 2019-11-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendientesEnviar',
            fields=[
                ('IDPendienteEnviar', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('NombreCortoProveedor', models.CharField(max_length=100)),
                ('FechaDescarga', models.CharField(max_length=100, null=True)),
                ('Moneda', models.CharField(max_length=10)),
                ('CostoSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('CostoTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Status', models.CharField(max_length=15)),
                ('IsFacturaCliente', models.BooleanField()),
                ('IsFacturaProveedor', models.BooleanField()),
                ('IsEvidenciaFisica', models.BooleanField()),
                ('IsEvidenciaDigital', models.BooleanField()),
            ],
            options={
                'db_table': 'PendientesEnviar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionConceptoxProyecto',
            fields=[
                ('RelacionIDConceptoxProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('IDConcepto', models.IntegerField(default=0)),
                ('IDCliente', models.IntegerField(default=0)),
                ('IDProveedor', models.IntegerField(default=0)),
                ('Proyecto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'RelacionConceptoxProyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturasxCliente',
            fields=[
                ('IDFactura', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=50, unique=True)),
                ('NombreCortoCliente', models.CharField(max_length=100)),
                ('FechaFactura', models.DateTimeField()),
                ('FechaRevision', models.DateTimeField()),
                ('FechaVencimiento', models.DateTimeField()),
                ('Moneda', models.CharField(max_length=10)),
                ('Subtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Retencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Saldo', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsAutorizada', models.BooleanField(default=False)),
                ('RutaXML', models.CharField(max_length=300)),
                ('RutaPDF', models.CharField(max_length=300)),
                ('TipoCambio', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('Comentarios', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'FacturasxCliente',
            },
        ),
        migrations.CreateModel(
            name='View_PendientesEnviarCxC',
            fields=[
                ('IDPendienteEnviar', models.ForeignKey(db_column='IDPendienteEnviar', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='PendienteEnviar.PendientesEnviar')),
                ('IDConcepto', models.IntegerField(default=0)),
                ('Folio', models.CharField(max_length=10, unique=True)),
                ('IDCliente', models.IntegerField(default=0)),
                ('NombreCliente', models.CharField(max_length=100)),
                ('FechaDescarga', models.CharField(max_length=100, null=True)),
                ('PrecioSubtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioIVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioRetencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('PrecioTotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Moneda', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=15)),
                ('IsEvidenciaDigital', models.BooleanField()),
                ('IsEvidenciaFisica', models.BooleanField()),
                ('Proyecto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'View_PendientesEnviarCxC',
                'managed': False,
            },
        ),
    ]
