# Generated by Django 2.1.13 on 2019-11-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('IDPartida', models.AutoField(primary_key=True, serialize=False)),
                ('FechaAlta', models.DateTimeField()),
                ('FechaBaja', models.DateTimeField()),
                ('Subtotal', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IVA', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Retencion', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('Total', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('IsActiva', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='RelacionFacturaxPartidas',
            fields=[
                ('IDRelacionFacturaxPartidas', models.AutoField(primary_key=True, serialize=False)),
                ('IDConcepto', models.IntegerField(default=0)),
                ('IDUsuarioAlta', models.IntegerField(default=0)),
                ('IDUsuarioBaja', models.IntegerField(default=0)),
                ('IDFacturaxCliente', models.ForeignKey(db_column='IDFacturaxCliente', on_delete=django.db.models.deletion.CASCADE, to='PendienteEnviar.FacturasxCliente')),
                ('IDPartida', models.ForeignKey(db_column='IDPartida', on_delete=django.db.models.deletion.CASCADE, to='PendienteEnviar.Partida')),
            ],
            options={
                'db_table': 'RelacionFacturaxPartidas',
            },
        ),
    ]
