# Generated by Django 2.1.13 on 2020-01-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionfacturaxpartidas',
            name='IDConcepto',
        ),
        migrations.AddField(
            model_name='relacionfacturaxpartidas',
            name='IDPendienteEnviar',
            field=models.ForeignKey(db_column='IDPendienteEnviar', default=1, on_delete=django.db.models.deletion.CASCADE, to='PendienteEnviar.PendientesEnviar'),
            preserve_default=False,
        ),
    ]
