# Generated by Django 2.1.13 on 2020-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasxcliente',
            name='IDCliente',
            field=models.IntegerField(default=0),
        ),
    ]
