# Generated by Django 2.1.13 on 2019-11-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0002_partida_relacionfacturaxpartidas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partida',
            table='Partida',
        ),
    ]
