# Generated by Django 2.1.13 on 2020-01-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersadmon', '0002_cliente'),
        ('PendienteEnviar', '0002_auto_20200103_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionfacturaxpartidas',
            name='IDUsuarioAlta',
        ),
        migrations.RemoveField(
            model_name='relacionfacturaxpartidas',
            name='IDUsuarioBaja',
        ),
        migrations.AddField(
            model_name='facturasxcliente',
            name='IDUsuarioAlta',
            field=models.ForeignKey(db_column='IDUsuarioAlta', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioAltaFactura', to='usersadmon.AdmonUsuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturasxcliente',
            name='IDUsuarioBaja',
            field=models.ForeignKey(db_column='IDUsuarioBaja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IDUsuarioBajaFactura', to='usersadmon.AdmonUsuarios'),
        ),
    ]
