# Generated by Django 2.1.13 on 2020-02-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0002_facturasxcliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasxcliente',
            name='Folio',
            field=models.CharField(max_length=50),
        ),
    ]
