# Generated by Django 2.1.13 on 2019-11-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0003_auto_20191108_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasxcliente',
            name='TotalConvertido',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
    ]
