# Generated by Django 2.1.13 on 2019-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0004_facturasxcliente_totalconvertido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='FechaBaja',
            field=models.DateTimeField(blank=True),
        ),
    ]
