# Generated by Django 2.1.13 on 2019-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0005_auto_20191112_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='FechaBaja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
