# Generated by Django 2.1.13 on 2019-11-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PendienteEnviar', '0006_auto_20191112_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasxcliente',
            name='Status',
            field=models.CharField(default='Pendiente', max_length=15),
        ),
    ]
